config/routes.rb
Rails.application.routes.draw do
  resources :respondents
  resources :campaigns
  resources :user_profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root "campaigns#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :campaign_respondents

  validates_presence_of :name
  validates_presence_of :typeof
  validates_presence_of :user_id
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /campaigns
  # GET /campaigns.json
  def index
    @user = current_user
    @campaign_count = Campaign.where(user_id: @user.id).count
    @user_campaigns = @user.campaigns
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @respondents_ids = CampaignRespondent.where(campaign_id: @campaign.id)
    @campaign_respondents = []
    @respondents_ids.each do |res|
      @campaign_respondents << Respondent.find_by(id: res.id)
    end
    @campaign_respondents = @campaign_respondents.compact
  end

  # GET /campaigns/new
  def new
    @user = current_user
    @campaign = current_user.campaigns.build
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @user = current_user
    @campaign = current_user.campaigns.build(campaign_params)
    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @user = current_user
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :name, :typeof)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :typeof %>
    <%= f.text_field :typeof %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<h1 class="text-center">Campaigns</h1>
<div class="col-md-3 text-center">
  <h3>Number of Campaigns: &nbsp;<strong><%= @campaign_count %></strong></h3>
</div>
<div class="col-md-6">
    <hr>
    <% @user_campaigns.each do |campaign| %>
        <h3 class="text-center"><%=link_to campaign.name, campaign, style: "font-size: 2rem;" %><h3>
    <% end %>
</div>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<div class="col-md-3">
  <br>
  <h3>Campaign Name: &nbsp;<strong><%= @campaign.name %></strong></h3>
  <br>
  <h4>Type of Campaign: <strong><%= @campaign.typeof %></strong></h4>
</div>
<div class="col-md-6 text-center">
<h1>Campaign Respondents</h1>

<table class="table offset2">
  <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Phone number</th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_respondents.each do |respondent| %>
      <tr>
        <td><%= respondent.name %></td>
        <td><%= respondent.email %></td>
        <td><%= respondent.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit Campaign', edit_campaign_path(@campaign), class: "btn btn-default" %> |
<%= link_to 'Destroy Campaign', @campaign, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
</div>