config/routes.rb
Rails.application.routes.draw do
  resources :respondents
  resources :campaigns
  resources :user_profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root "campaigns#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/respondent.rb
class Respondent < ApplicationRecord
  belongs_to :user
  has_many :campaign_respondents

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :phone_number
  validates_presence_of :user_id
end

app/controllers/respondents_controller.rb
class RespondentsController < ApplicationController
  before_action :set_respondent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /respondents
  # GET /respondents.json
  def index
    @respondents = Respondent.all
  end

  # GET /respondents/1
  # GET /respondents/1.json
  def show
  end

  # GET /respondents/new
  def new
    @respondent = current_user.build_respondent
  end

  # GET /respondents/1/edit
  def edit
  end

  # POST /respondents
  # POST /respondents.json
  def create
    @respondent = current_user.build_respondent(respondent_params)

    respond_to do |format|
      if @respondent.save
        format.html { redirect_to @respondent, notice: 'Respondent was successfully created.' }
        format.json { render :show, status: :created, location: @respondent }
      else
        format.html { render :new }
        format.json { render json: @respondent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /respondents/1
  # PATCH/PUT /respondents/1.json
  def update
    respond_to do |format|
      if @respondent.update(respondent_params)
        format.html { redirect_to @respondent, notice: 'Respondent was successfully updated.' }
        format.json { render :show, status: :ok, location: @respondent }
      else
        format.html { render :edit }
        format.json { render json: @respondent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /respondents/1
  # DELETE /respondents/1.json
  def destroy
    @respondent.destroy
    respond_to do |format|
      format.html { redirect_to respondents_url, notice: 'Respondent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_respondent
      @respondent = Respondent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def respondent_params
      params.require(:respondent).permit(:user_id, :name, :email, :phone_number)
    end
end

app/helpers/respondents_helper.rb
module RespondentsHelper
end

app/views/respondents/_form.html.erb
<%= form_for(respondent) do |f| %>
  <% if respondent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(respondent.errors.count, "error") %> prohibited this respondent from being saved:</h2>

      <ul>
      <% respondent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/respondents/edit.html.erb
<h1>Editing Respondent</h1>

<%= render 'form', respondent: @respondent %>

<%= link_to 'Show', @respondent %> |
<%= link_to 'Back', respondents_path %>

app/views/respondents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Respondents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @respondents.each do |respondent| %>
      <tr>
        <td><%= respondent.name %></td>
        <td><%= respondent.email %></td>
        <td><%= respondent.phone_number %></td>
        <td><%= link_to 'Show', respondent %></td>
        <td><%= link_to 'Edit', edit_respondent_path(respondent) %></td>
        <td><%= link_to 'Destroy', respondent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Respondent', new_respondent_path %>

app/views/respondents/new.html.erb
<h1>New Respondent</h1>

<%= render 'form', respondent: @respondent %>

<%= link_to 'Back', respondents_path %>

app/views/respondents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @respondent.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @respondent.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @respondent.phone_number %>
</p>

<%= link_to 'Edit', edit_respondent_path(@respondent) %> |
<%= link_to 'Back', respondents_path %>